### PR TITLE
BUG: Remove CircleCI configuration

### PR DESCRIPTION
**Pull request by thewtex**
This is no longer needed since we have an Azure Pipelines setup and is
throwing false positive failures.

### CODE REVIEW

**Comment by thewtex** [comment]
@ctrueden it seems I have partial permissions on the CircleCI configuration. I disabled it for forked PR's, but I could not remove it completely for this repository. Do you have that option?

**Comment by ctrueden** [comment]
@thewtex Sorry, I don't think I've ever authenticated with CircleCI. Someone else must have set it up here. Based on 98ddc5bc41dd68d25bb824521c9b0bcb5bc96afa, maybe it was @blowekamp ?

**Comment by blowekamp** [comment]
Let me see if I have any access.

**Comment by blowekamp** [comment]
Nope, I don't have admin access in CircleCI to SCIFIO either.

**Comment by hjmjohnson** [comment]
I was able to delete the webhook.  I don't ever remember setting it up, but perhaps I did.

**Comment by thewtex** [comment]
> Looks good. Should we remove all .circleci/config.yml?

We could remove them, but we should disable/remove the builds beforehand so they do not complain about a missing configuration.

> I was able to delete the webhook.

Thanks!

**Pull request merged**
