### PR TITLE
ENH: Updating CI from ITKModuleTemplate

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
I enabled CircleCI building on my fork. Who has access to setup CI on CircleCI/Travis and Appveyor?

**Comment by ctrueden** [comment]
@blowekamp I enabled Travis CI builds for this repository, as well as AppVeyor builds using our dedicated `scijava-ci` account:

* https://travis-ci.org/scifio/scifio-imageio
* https://ci.appveyor.com/project/scijava/scifio-imageio

I have no experience with Circle CI. But you are an admin for this repository, so hopefully it is possible for you to do it yourself? If not, and there is something I can do to help, please let me know.

**Comment by thewtex** [comment]
@blowekamp @ctrueden excellent! @blowekamp note that `itkrobot` will need to be changed to `scijava` in some spots. CircleCI is building :-)

**Comment by thewtex** [comment]
I don't think we will be able to generate the distributable Python wheels unless we build scifio to C, then link it into the C extension. @ctrueden is this feasible now with GraalVM?

**Comment by blowekamp** [comment]
The downloaded could not be loaded:
```
/ITK-build/lib/jre/bin # ldd java
	/lib64/ld-linux-x86-64.so.2 (0x558961b60000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x558961b60000)
Error loading shared library libjli.so: No such file or directory (needed by java)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x558961b60000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x558961b60000)
Error relocating java: JLI_WildcardExpandClasspath: symbol not found
Error relocating java: JLI_MemFree: symbol not found
Error relocating java: JLI_ParseManifest: symbol not found
Error relocating java: JLI_ExactVersionId: symbol not found
Error relocating java: JLI_JarUnpackFile: symbol not found
Error relocating java: JLI_AcceptableRelease: symbol not found
Error relocating java: JLI_FreeManifest: symbol not found
Error relocating java: JLI_StringDup: symbol not found
Error relocating java: JLI_ValidVersionString: symbol not found
Error relocating java: JLI_MemAlloc: symbol not found
```

We now install java on the system.

I would also like to raise the question if it make since to by default use an old downloaded JRE.

**Comment by thewtex** [comment]
For Python wheel packages, it is best to not assume that `java` is installed or available.

**Comment by ctrueden** [comment]
> build scifio to C, then link it into the C extension. @ctrueden is this feasible now with GraalVM?

I did not try it yet. However, the obstacles I anticipate are:

- SCIFIO is fundamentally plugin-driven. Graal's AoT `native-image` compiler currently requires that all Java classes in the mix be fully discerned/specified. In other words: no dynamic class loading from AoT-compiled libraries right now. I believe they are planning to improve that in a future release, but it is probably months-to-years away.
- SCIFIO needs to be modularized so that we can cherry pick which formats to AoT compile. Some of them—ones with lots of deps and/or using exotic Java APIs such as `javax.xml` or whatnot—are less likely to AoT compile cleanly right now.
- This [SCIFIO ITK bridge library](https://github.com/scifio/scifio-itk-bridge) actually uses Bio-Formats directly right now, not the SCIFIO framework. At some point in the future, I would like to update that library to use SCIFIO. In the meantime, the prior two concerns about being plugin-driven and not modular enough apply to Bio-Formats as well.

I know next to nothing about Python wheels. What is the challenge with generating distributable Python wheels? Why would we need to compile the Java code into native code?

**Comment by blowekamp** [comment]
I would like to just get the C++ building working and testing to update the core library. There are a number of failures related to python packaging I don't wish to pursue.

**Comment by thewtex** [comment]
>  However, the obstacles I anticipate are:

Excellent, thanks for the information.

> I know next to nothing about Python wheels. What is the challenge with generating distributable Python wheels? Why would we need to compile the Java code into native code?

There is no Python wheel package (that I am aware of) that provides a JVM.

> I would like to just get the C++ building working and testing to update the core library. There are a number of failures related to python packaging I don't wish to pursue.

In this case, the AppVeyor and TravisCI configuration can be removed / disabled, and the `ci/circleci: package` configuration can be disabled.

**Comment by blowekamp** [comment]
I don't have access to disabling appveyor now. @ctrueden 

It looks like we have CircleCI working now, so I'm merging to work on the updates...

**Pull request merged**
